import Head from "next/head";

import Header from "@/components/Header";

export default function Home() {

  return (
    <>
      <Head>
        <title>La Roti Bakery</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
      </main>
    </>
  );
}
